# Generated by Django 5.2.17 on 2026-08-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
