# Generated by Django 5.2.17 on 2026-08-22 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['is_completed', '-created_at']},
        ),
        migrations.AlterField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'is_completed'], name='goals_goal_user_id_c14f76_idx'),
        ),
    ]
