# Generated by Django 5.2.17 on 2026-08-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], db_index=True, default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['muscle_group', 'difficulty'], name='exercises_e_muscle__2bcd2f_idx'),
        ),
    ]
