# Generated by Django 5.2.17 on 2026-08-22 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_options_alter_exercise_difficulty_and_more'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['set_number', 'id']},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.exercise'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'date'], name='workouts_wo_user_id_f1c995_idx'),
        ),
        migrations.AddConstraint(
            model_name='set',
            constraint=models.UniqueConstraint(fields=('workout_exercise', 'set_number'), name='unique_set_number_per_workout_exercise'),
        ),
    ]
